name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Config Enviroments
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        username:  ${{ secrets.REMOTE_USER }}
    - name: Config Enviroments
      run: |
        ls -la
        echo "Aquiii"