name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    steps:
    - name: pass environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        username:  ${{ secrets.REMOTE_USER }}
        run: |
          git config user.name pablicio
          git config github.token ${{ secrets.GITHUB_TOKEN }}
          git clone https://github.com/pablicio/c4-model-service-test.git
        working-directory: /home/ubuntu/repos