name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
    - name: Create folder
      run: |
        sudo mkdir -p /home/ubuntu/docs/c4-model-service-test-2/
    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "--atimes --times --crtimes"
        SOURCE: "./sophya-docs/"
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        TARGET: '/home/ubuntu/docs/c4-model-service-test-2/'