name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Sync Documentation Folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        username:  ${{ secrets.REMOTE_USER }}
        script: |
  
          cd /home/ubuntu/repos/c4-model-service-test
          ls -la