name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Sync Documentation Folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        username:  ${{ secrets.REMOTE_USER }}
        script: |
          if [[ -f /home/ubuntu/repos/c4-model-service-test/README.md ]]; then
            cd /home/ubuntu/repos/c4-model-service-test
            git fetch
            git diff --name-only origin/main 2>/dev/null | egrep '\.(puml)$' >> /home/ubuntu/docs/diff.json
            git pull
          else
            git config user.name pablicio
            git config github.token ${{ secrets.GITHUB_TOKEN }}
            git clone https://github.com/pablicio/c4-model-service-test.git /home/ubuntu/repos/c4-model-service-test 2>/dev/null
          fi
    - name: Sync doc folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        username:  ${{ secrets.REMOTE_USER }}
        script: |
          rsync -rltgoDzvO --delete /home/ubuntu/repos/c4-model-service-test/sophya-docs /home/ubuntu/docs/c4-model-service-test/