name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
    - name: Set Github token
      run: |
        git config user.name pablicio
        git config github.token ${{ secrets.TOKEN_GIT_REPO }}
    - name: Create folder for documentation
      run: |
        sudo mkdir -p /home/ubuntu/docs/c4-model-service-test/
    - name: Clone Project folder
      run: |
        git clone https://github.com/pablicio/c4-model-service-test.git
      working-directory: /home/ubuntu/repos
