name: Generate Documentation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Sync Documentation Folder
      uses: appleboy/ssh-action@master
      env: 
        REPO_NAME: c4-model-service-test
        GIT_USER: pablicio
        FILE_CHECK: README.md
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.EC2_SSH_KEY }}
        username:  ${{ secrets.REMOTE_USER }}
        script: |
          sh sync_repo.sh $REPO_NAME $GIT_USER ${{ secrets.GITHUB_TOKEN }} $FILE_CHECK
          sh sync_docs.sh $REPO_NAME